# Function to output printed text

output_print <- function(ME, focus, eff_eff, beta_threshhold, nu, obs_r, critical_r, r_con, itcv, alpha, index) {
  if (ME == T) {
    cat("These calculations assume measurement error as specified by the user. Different calculations would apply to an inference assuming no measurement error. If you prefer those calculations, rerun the command specifying no measurement error as in conmed_ind().")
  }
  if (focus == "inval_a") {
      cat("To invalidate an inference of a significant mediation effect, we consider an omitted confounder CV to change the inference regarding the a pathway (from the treatment to the mediator).")
      cat("The minimum impact as defined by Frank 2000 (the product of rX,CV and rM,CV) would be ")
      cat(round(r_con^2, 3), "to invalidate an inference for a null hypothesis of 0 pathway.")
      cat("This is generated by a scenario that generates the smallest impact necessary to invalidate the inference where |rX,CV| = |rM,CV| = ", r_con)
      cat(" (conditioning on observed covariates). The correlation is also based on a threshold of ")
      cat(round(critical_r, 3), " for statistical significance (alpha = ", alpha, ").\n", sep = "")
      cat("\n")
      cat("Other combinations of rX,CV and rM,CV with impacts greater than", round(r_con, 2), "can change the inference. These are shown on the impact curve below for which any combinations of correlations on or above the curved line would invalidate the inference regarding the a pathway.")
      cat(" Accordingly, the mediation effect via M is not significant anymore, based on a joint significance test.")
      }
  if (focus == "inval_b") {
      cat("To invalidate an inference of a significant mediation effect, we consider an omitted confounder CV to change the inference regarding the b pathway (from the mediator to the outcome).")
      cat("The minimum impact defined by Frank 2000 (the product of rM,CV and rY,CV) would be ")
      cat(round(r_con^2, 3), "to invalidate an inference for a null hypothesis of 0 pathway.")
      cat("This is generated by a scenario that generates the smallest impact necessary to invalidate the inference where |rM,CV| = |rY,CV| = ", r_con)
      cat(" (conditioning on observed covariates). The correlation is also based on a threshold of ")
      cat(round(critical_r, 3), " for statistical significance (alpha = ", alpha, ").\n", sep = "")
      cat("\n")
      cat("Other combinations of rM,CV and rY,CV with impacts greater than", round(r_con, 2), "can change the inference. These are shown on the impact curve below for which any combinations of correlations on or above the curved line would invalidate the inference regarding the b pathway.")
      cat(" Accordingly, the mediation effect via M is not significant anymore, based on a joint significance test.")
      }
  if (focus == "sustain_a") {
      cat("To sustain an inference of a significant mediation effect, we consider an omitted confounder to change the inference regarding the a pathway (from the treatment to the mediator).")
      cat("The maximum impact defined by Frank 2000 (the product of rX,CV and rM,CV) would be ")
      cat(round(r_con^2, 3), "to sustain an inference that the a pathway is statistically significant from 0.")
      cat("This is generated by a scenario that generates the largest impact necessary to sustain the inference where |rX,CV| = |rM,CV| = ", r_con)
      cat(" (conditioning on observed covariates). The correlation is also based on a threshold of ")
      cat(round(critical_r, 3), " for statistical significance (alpha = ", alpha, ").\n", sep = "")
      cat(" Accordingly, the mediation effect via M is statistically significant, based on a joint significance test.")
  }
  if (focus == "sustain_b") {
    cat("To sustain an inference of a significant mediation effect, we consider an omitted confounder to change the inference regarding the b pathway (from the mediator to the outcome).")
    cat("The maximum impact defined by Frank 2000 (the product of rM,CV and rY,CV) would be ")
    cat(round(r_con^2, 3), "to sustain an inference that the b pathway is statistically significant from 0.")
    cat("This is generated by a scenario that generates the largest impact necessary to sustain the inference where |rM,CV| = |rY,CV| = ", r_con)
    cat(" (conditioning on observed covariates). The correlation is also based on a threshold of ")
    cat(round(critical_r, 3), " for statistical significance (alpha = ", alpha, ").\n", sep = "")
    cat(" Accordingly, the mediation effect via M is statistically significant, based on a joint significance test.")
  }
}
